### ISSUE TITLE
A quick question about UKBB dataset

### ISSUE THREAD

**Issue by HelloWorldLTY** [bioDS/snvformer#1]
Hi, I am pretty interested in you work about GWAS+transformer work. I wonder if it is possible for me to access your training/testing datasets to get faimilar with the formart of such data. Thanks a lot.

**Comment by kollienne** [comment]
To access the UK Biobank specifically you will need to apply here: https://www.ukbiobank.ac.uk/enable-your-research/apply-for-access.

If you're just after something in the same format there is some example plink data here https://zzz.bwh.harvard.edu/plink/hapmap1.zip.
